<a href="https://colab.research.google.com/github/mr-cri-spy/machine-_-learning-/blob/main/numpy_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Preprocessing

Data preprocessing is the process of cleaning, transforming, and organizing raw data into a format that’s easier to analyze and use

Libraries That Make Preprocessing Easy:
*numpy
*pandas
*matplotlib/seaborn

lets first dive in to numpy we use to work on array type of data
*Great for numerical operations and handling arrays

array is nothing but a group or similar elements like integers, string, float

first import libraries


In [ ]:
import numpy as np

creating 1D array


In [ ]:
a1 = np.array([1,2,3,4,5])

Ok lets see what type of this using type function

In [ ]:
print(type(a1))

<class 'numpy.ndarray'>


nd-array means N dimention array

if we want to check dimention of this

In [ ]:
print(a1.ndim)

1


which shows 1 means 1 dimention, ndim mean N dimention

if we want to know length of the data

In [ ]:
print(len(a1))

5


if we want to see what is the datatype of the element in an array

In [ ]:
print(a1.dtype)

int64


which means integer 64

lets create 2d array

In [ ]:
a2 = np.array([[1,2,3,4,5]])

lets make same process what we did for 1d array


In [ ]:
print(f"The type of this data is {type(a2)}")
print(f"dimention of this data is {a2.ndim}")
print(f"length of this data is {len(a2)}")
print(f"type of this data is {a2.dtype}")


The type of this data is <class 'numpy.ndarray'>
dimention of this data is 2
length of this data is 1
type of this data is int64


array in maths

In [ ]:
print(a1+a2)

[[ 2  4  6  8 10]]


know the shape of array , to knowing the number of elements

In [ ]:
print(a1.shape)
print(a2.shape)

(5,)
(1, 5)


creating 2d array


In [ ]:
a3 = np.array([[1,2,3],[4,5,6]])

making the process which did before

In [ ]:
print(f"The type of this data is {type(a3)}")
print(f"dimention of this data is {a3.ndim}")
print(f"length of this data is {len(a3)}")
print(f"type of this data is {a3.dtype}")


The type of this data is <class 'numpy.ndarray'>
dimention of this data is 2
length of this data is 2
type of this data is int64


we can know the sum of data on this way

In [ ]:
print(f"the sum of 2d array a3 : {sum(a3)}")

the sum of 2d array a3 : [5 7 9]


creating 3d array

In [ ]:
a4 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

same process to know about this data

In [ ]:
print(f"The type of this data is {type(a4)}")
print(f"dimention of this data is {a4.ndim}")
print(f"length of this data is {len(a4)}")
print(f"type of this data is {a4.dtype}")



The type of this data is <class 'numpy.ndarray'>
dimention of this data is 3
length of this data is 1
type of this data is int64


benifits of array : array is better to make doing calculation and operation

In [ ]:
print(a4.shape)

(1, 3, 3)


this mean 1 3d array which found , 3 1d arrays which found and , in each 3 elements

In [ ]:
IS = np.array([[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]])


array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

lets see index of IS

In [ ]:
print(f"the index of IS[O] index is {IS[0]}")

the index of IS[O] index is [1 2 3 4 5]


In [ ]:
IS[1:3,1:4]   ## row , column

array([[ 20,  30,  40],
       [200, 300, 400]])

where giving index 1 to index of 2 rows 1:3
where giving index 1 to index of 3 column 1:4 when chosing na in last of indexing that time we should give extra one like i need 1 to 2 index but i want to put 2 to place of 3 should give one extra index and : means all like  if my index is ther till 5 k if i use 1: like this it ll be take till 5 index

numpy functions
sum , mean, max argmax, argmin

In [ ]:
print(a1.max())
print(a1.min())
print(a1.mean())
print(a1.argmax())
print(a1.argmin())

5
1
3.0
4
0


In [ ]:
print(a4.max())
print(a4.min())
print(a4.mean())
print(a4.argmax(axis=0)) ###column wise
print(a4.argmin(axis=1)) ###row wise

9
1
5.0
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]]


reshape function : sed to change the shape of an array

In [ ]:
print(a1.shape)

(5,)


In [ ]:
a1 = a1.reshape(5,1)
a1.shape

(5, 1)

if i want to generate zero matrix

In [ ]:
zero_matrix = np.zeros((3,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


if i want to create 1s matrix

In [ ]:
ones_matrix = np.ones((3,3))
print(ones_matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


if we want to create identity matrix: it is  a diagonal matrix with all its diagonal elements equal to 1 , and zeroes everywhere else

In [ ]:
i = np.identity(3)
i




array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###which will be always data type is float

In [ ]:
i.dtype

dtype('float64')

if we want to change data type:->

In [ ]:
i = i.astype("int")
i.dtype


dtype('int64')

In [ ]:
i= i.astype("float")
i.dtype

dtype('float64')

this is how numpy library is using, Thank You